name: build-windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  win-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          # Fallback if requirements.txt is missing Pillow:
          pip install pillow
          pip install pyinstaller

      - name: Build Windows EXE with PyInstaller
        shell: pwsh
        run: |
                   $iconArg = @()
          if (Test-Path 'assets\icon.ico') { $iconArg = @('--icon', 'assets\icon.ico') }
          if (-not (Test-Path 'main.py')) { throw 'main.py not found at repo root.' }

          # --collect-all PIL ensures Image plugins (PNG/JPEG, etc.) get bundled
          pyinstaller --name KurashScoreboard --onefile --windowed `
            --collect-all PIL `
            --add-data "Sounds;Sounds" `
            --add-data "Flags;Flags" `
            @iconArg main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: KurashScoreboard-win
          path: dist/KurashScoreboard.exe
