name: build-windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  win-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          # Ensure critical build deps exist even if requirements.txt is missing entries
          pip install pillow pyinstaller

      - name: Build Windows EXE with PyInstaller
        shell: pwsh
        run: |
          # Optional icon (safe if missing)
          $iconArg = @()
          if (Test-Path 'assets\icon.ico') { $iconArg = @('--icon', 'assets\icon.ico') }

          # Ensure entry exists (adjust if not main.py)
          if (-not (Test-Path 'main.py')) { throw 'main.py not found at repo root.' }

          # Build (Windows uses ; in --add-data). Bundle PIL plugins & tk bridge.
          pyinstaller --name KurashScoreboard --onefile --windowed `
            --collect-all PIL `
            --hidden-import PIL._tkinter_finder `
            --add-data "Sounds;Sounds" `
            --add-data "Flags;Flags" `
            @iconArg main.py

          # Verify output
          if (-not (Test-Path 'dist\KurashScoreboard.exe')) {
            Write-Error "Build finished but dist\KurashScoreboard.exe not found."
            exit 1
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: KurashScoreboard-win
          path: dist/KurashScoreboard.exe

